### ISSUE TITLE
question about stage-1 training

### ISSUE THREAD

**Issue by Gloriabhsfer** [pairlab/QueST#13]
Hi,
Thanks for your great works. I am trying to train the stage-1 training after the stage-0 training for task libero-90, it works well until 25 episodes and hydra show me:

`Traceback (most recent call last):
  File "/home/yu/anaconda3/envs/quest/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/yu/anaconda3/envs/quest/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yu/LIBERO/libero/libero/envs/venv.py", line 231, in _worker
    env = env_fn_wrapper.data()
  File "/home/yu/QueST/quest/env_runner/libero_runner.py", line 94, in <lambda>
    env_fn = lambda: lu.LiberoFrameStack(self.env_factory(env_id, self.benchmark), self.frame_stack)
  File "/home/yu/QueST/quest/utils/libero_utils.py", line 116, in __init__
    env = OffScreenRenderEnv(**env_args)
  File "/home/yu/LIBERO/libero/libero/envs/env_wrapper.py", line 161, in __init__
    super().__init__(**kwargs)
  File "/home/yu/LIBERO/libero/libero/envs/env_wrapper.py", line 47, in __init__
    controller_configs = suite.load_controller_config(default_controller=controller)
AttributeError: module 'robosuite' has no attribute 'load_controller_config'`
It seems my version for robosuite not right? the robosuite version is robosuite  1.4.1 which I installed from source code, did you seen this question before? Could you please gave me some ideas?

**Comment by atharvamete** [comment]
Hi, I also have robosuite 1.4.1 but never got this error before. Could you check if robosuite working correctly on its own?
