### ISSUE TITLE
train_error

### ISSUE THREAD

**Issue by LogSSim** [pairlab/QueST#5]
Thanks for your contributions. When I run the train.py(python train.py --config-name=train_autoencoder.yaml ). There is a problem：

'''
starting from scratch
Error executing job with overrides: ['task=libero_90', 'algo=quest', 'exp_name=final', 'variant_name=block_32_ds_4', 'algo.skill_block_size=32', 'algo.downsample_factor=4', 'seed=0']
Error locating target 'quest.utils.libero_utils.build_dataset', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task.dataset

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
'''

How could I fix it?

**Comment by atharvamete** [comment]
Hi,
please set HYDRA_FULL_ERROR=1 to see the full-error
you can do this by `export HYDRA_FULL_ERROR=1` in terminal before running the training command

**Comment by LogSSim** [comment]
> Hi, please set HYDRA_FULL_ERROR=1 to see the full-error you can do this by `export HYDRA_FULL_ERROR=1` in terminal before running the training command

Thanks for your reply. I run this code in windows 10. But I got this error.
'''
Error executing job with overrides: ['task=libero_90']
Traceback (most recent call last):
  File "D:\ALL_files\code\QueST\test.py", line 31, in main
    for data in train_dataloader:
  File "E:\ProgramData\anaconda3\envs\quest\lib\site-packages\torch\utils\data\dataloader.py", line 701, in __next__
    data = self._next_data()
  File "E:\ProgramData\anaconda3\envs\quest\lib\site-packages\torch\utils\data\dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "E:\ProgramData\anaconda3\envs\quest\lib\site-packages\torch\utils\data\dataloader.py", line 1491, in _process_data
    data.reraise()
  File "E:\ProgramData\anaconda3\envs\quest\lib\site-packages\torch\_utils.py", line 715, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\quest\lib\site-packages\torch\utils\data\_utils\worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "E:\ProgramData\anaconda3\envs\quest\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\ProgramData\anaconda3\envs\quest\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\ProgramData\anaconda3\envs\quest\lib\site-packages\torch\utils\data\dataset.py", line 350, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "D:\ALL_files\code\QueST\quest\utils\libero_utils.py", line 292, in __getitem__
    return_dict = self.sequence_dataset.__getitem__(idx)
  File "D:\ALL_files\code\QueST\quest\utils\dataset.py", line 420, in __getitem__
    return self.get_item(index)
  File "D:\ALL_files\code\QueST\quest\utils\dataset.py", line 458, in get_item
    meta["obs"] = self.get_obs_sequence_from_demo(
  File "D:\ALL_files\code\QueST\quest\utils\dataset.py", line 607, in get_obs_sequence_from_demo
    return ObsUtils.process_obs_dict(obs)
  File "D:\ALL_files\code\QueST\quest\utils\obs_utils.py", line 365, in process_obs_dict
    return { k : process_obs(obs=obs, obs_key=k) for k, obs in obs_dict.items() } # shallow copy
  File "D:\ALL_files\code\QueST\quest\utils\obs_utils.py", line 365, in <dictcomp>
    return { k : process_obs(obs=obs, obs_key=k) for k, obs in obs_dict.items() } # shallow copy
  File "D:\ALL_files\code\QueST\quest\utils\obs_utils.py", line 350, in process_obs
    obs_modality = OBS_KEYS_TO_MODALITIES[obs_key]
TypeError: 'NoneType' object is not subscriptable
'''

**Comment by Triumphant-strain** [comment]
Hi, thanks for your impressive work!
I've met the same question, could you please help me out?
Here are the logs:
starting from scratch
Error executing job with overrides: []
Traceback (most recent call last):
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'quest.utils' has no attribute 'libero_utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/data/anaconda3/envs/quest/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/xjk/QueST-main/quest/utils/libero_utils.py", line 5, in <module>
    import gymnasium
ModuleNotFoundError: No module named 'gymnasium'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'quest.utils.libero_utils.build_dataset':
ModuleNotFoundError("No module named 'gymnasium'")
Are you sure that 'libero_utils' is importable from module 'quest.utils'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/xjk/QueST-main/train.py", line 194, in <module>
    main()
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/data/xjk/QueST-main/train.py", line 77, in main
    dataset = instantiate(cfg.task.dataset)
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/data/anaconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'quest.utils.libero_utils.build_dataset', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task.dataset
