### ISSUE TITLE
`./scripts/dp/main.sh` not working

### ISSUE THREAD

**Issue by junh0cho** [pairlab/QueST#8]
I have tried running all experiments of other algos too.
I have found following scripts working fine:
```
.
├── act
│   ├── finetune.sh  (haven't tried)
│   └── main.sh    (training works)
├── bc_trans
│   ├── finetune.sh  (haven't tried)
│   └── main.sh    (training works)
├── bet
│   ├── autoencoder.sh    (training works)
│   ├── finetune.sh  (haven't tried)
│   └── main.sh  (haven't tried)
├── dp
│   ├── finetune.sh  (haven't tried)
│   └── main.sh    (XXXX training not working)
└── quest
    ├── autoencoder.sh    (training works)
    ├── finetune.sh  (haven't tried)
    └── main.sh  (haven't tried)
```
`./scripts/dp/main.sh` fails with following error
```
(quest) ➜  QueST git:(main) ✗ CUDA_VISIBLE_DEVICES=3  HYDRA_FULL_ERROR=1  ./scripts/dp/main.sh
Error executing job with overrides: ['task=libero_90', 'algo=diffusion_policy', 'exp_name=final', 'variant_name=block_32', 'training.use_tqdm=false', 'training.save_all_checkpoints=true', 'training.use_amp=false', 'training.n_epochs=200', 'train_dataloader.persistent_workers=true', 'train_dataloader.num_workers=6', 'make_unique_experiment_dir=false', 'algo.skill_block_size=32', 'training.auto_continue=true', 'rollout.num_parallel_envs=5', 'rollout.rollouts_per_env=5', 'seed=0']
Traceback (most recent call last):
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'quest.algos' has no attribute 'diffusion_policy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/junho/workspace/QueST/quest/algos/diffusion_policy.py", line 5, in <module>
    from diffusers.training_utils import EMAModel
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/huggingface_hub/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'quest.algos.diffusion_policy.DiffusionPolicy':
ImportError("cannot import name 'cached_download' from 'huggingface_hub' (/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/huggingface_hub/__init__.py)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/junho/workspace/QueST/train.py", line 190, in <module>
    main()
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/junho/workspace/QueST/train.py", line 29, in main
    model = instantiate(cfg.algo.policy,
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'quest.algos.diffusion_policy.DiffusionPolicy', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: algo.policy
```
Seems like `quest.algos.diffusion_policy.DiffusionPolicy` is not reachable?
Having a look on `./config/algo/diffusion_policy.yaml`
```
...
policy:
  _target_: quest.algos.diffusion_policy.DiffusionPolicy
  diffusion_model:
    _target_: quest.algos.diffusion_policy.DiffusionModel
...
```
looks reasonable too me... 
Since I am not familiar with hydra, I have some trouble looking for reason to make dp works. any idea?

**Comment by atharvamete** [comment]
> File "/home/junho/workspace/QueST/quest/algos/diffusion_policy.py", line 5, in <module>
    from diffusers.training_utils import EMAModel
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/junho/miniconda3/envs/quest/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub'

As you can see in this line, the issue is with importing diffusers
As per latest comments on this [thread](https://github.com/easydiffusion/easydiffusion/issues/1851) downgrading huggingface-hub version should do the job.

**Comment by junh0cho** [comment]
Thank you, downgrading `huggingface-hub` helped!  `pip install huggingface-hub==0.25.2` 

Another question here, is there reason we need `training.auto_continue=true \` when trainig dp? 
https://github.com/pairlab/QueST/blob/1d147e162eaebc61874b8b53c4d502cb2806e79d/scripts/dp/main.sh#L17
`training.auto_continue=true \` requires stage-0 like quest and vqbet but dp seems not training autoencoder.
Without this line, dp is trained without problem

**Comment by atharvamete** [comment]
That's correct. Thanks for pointing it out.
